import type { Demande } from "@d-red/types";
import { ilYA } from "./temps.js";

/** Une demande par statut du cycle, pour peupler les dashboards (WH-02/WC-01) sans écran vide. */
export const demandes: Demande[] = [
  {
    id: "dem_1",
    etablissementId: "etab_hopital_principal_dakar",
    groupeSanguin: "O-",
    produit: "CONCENTRE_GLOBULAIRE",
    niveauUrgence: "CRITIQUE",
    status: "CREATED",
    createdAt: ilYA(0),
  },
  {
    id: "dem_2",
    etablissementId: "etab_clinique_pasteur",
    groupeSanguin: "A+",
    produit: "PLASMA",
    niveauUrgence: "PRIORITAIRE",
    status: "SCANNING_INFRAS",
    createdAt: ilYA(2),
  },
  {
    id: "dem_3",
    etablissementId: "etab_cnts_dakar",
    groupeSanguin: "A+",
    produit: "SANG_TOTAL",
    niveauUrgence: "CRITIQUE",
    status: "DONORS_NOTIFIED",
    createdAt: ilYA(4),
  },
  {
    id: "dem_4",
    etablissementId: "etab_hopital_principal_dakar",
    groupeSanguin: "O-",
    produit: "CONCENTRE_GLOBULAIRE",
    niveauUrgence: "CRITIQUE",
    status: "PRE_RESERVED",
    createdAt: ilYA(8),
    donneurAssigneId: "don_aissatou_ba",
  },
  {
    id: "dem_5",
    etablissementId: "etab_hopital_thies",
    groupeSanguin: "AB-",
    produit: "PLAQUETTES",
    niveauUrgence: "PRIORITAIRE",
    status: "EN_ROUTE",
    createdAt: ilYA(15),
    donneurAssigneId: "don_khady_fall",
  },
  {
    id: "dem_6",
    etablissementId: "etab_clinique_pasteur",
    groupeSanguin: "A+",
    produit: "SANG_TOTAL",
    niveauUrgence: "STANDARD",
    status: "ARRIVED",
    createdAt: ilYA(40),
    donneurAssigneId: "don_fatou_sow",
  },
  {
    id: "dem_7",
    etablissementId: "etab_hopital_principal_dakar",
    groupeSanguin: "O+",
    produit: "SANG_TOTAL",
    niveauUrgence: "STANDARD",
    status: "DONATION_COMPLETED",
    createdAt: ilYA(70),
    donneurAssigneId: "don_moussa_diop",
  },
  {
    id: "dem_8",
    etablissementId: "etab_cnts_dakar",
    groupeSanguin: "B+",
    produit: "CONCENTRE_GLOBULAIRE",
    niveauUrgence: "CRITIQUE",
    status: "CLOSED",
    createdAt: ilYA(150),
    donneurAssigneId: "don_ibrahima_ndiaye",
  },
];
