import type { Donneur } from "@d-red/types";

export const donneurs: Donneur[] = [
  {
    id: "don_aissatou_ba",
    nom: "Aïssatou Ba",
    telephone: "+221 77 123 45 01",
    groupeSanguin: "O-",
    canalAlertePrefere: "PUSH",
    statutVerification: "VERIFIE",
    disponible: true,
    position: { lat: 14.6862, lng: -17.4479 },
    nombreDonsEffectues: 6,
  },
  {
    id: "don_moussa_diop",
    nom: "Moussa Diop",
    telephone: "+221 77 123 45 02",
    groupeSanguin: "O-",
    canalAlertePrefere: "APPEL",
    statutVerification: "VERIFIE",
    disponible: true,
    position: { lat: 14.7167, lng: -17.4677 },
    nombreDonsEffectues: 2,
  },
  {
    id: "don_fatou_sow",
    nom: "Fatou Sow",
    telephone: "+221 77 123 45 03",
    groupeSanguin: "A+",
    canalAlertePrefere: "SMS",
    statutVerification: "VERIFIE",
    disponible: true,
    position: { lat: 14.6634, lng: -17.4224 },
    nombreDonsEffectues: 4,
  },
  {
    id: "don_ibrahima_ndiaye",
    nom: "Ibrahima Ndiaye",
    telephone: "+221 77 123 45 04",
    groupeSanguin: "B+",
    canalAlertePrefere: "PUSH",
    statutVerification: "VERIFIE",
    disponible: false,
    position: { lat: 14.7645, lng: -17.3660 },
    nombreDonsEffectues: 1,
  },
  {
    id: "don_khady_fall",
    nom: "Khady Fall",
    telephone: "+221 77 123 45 05",
    groupeSanguin: "AB-",
    canalAlertePrefere: "PUSH",
    statutVerification: "VERIFIE",
    disponible: true,
    position: { lat: 14.7000, lng: -17.4700 },
    nombreDonsEffectues: 9,
  },
  {
    id: "don_omar_gueye",
    nom: "Omar Gueye",
    telephone: "+221 77 123 45 06",
    groupeSanguin: "O+",
    canalAlertePrefere: "APPEL",
    statutVerification: "NON_VERIFIE",
    disponible: true,
    position: { lat: 14.6900, lng: -17.4300 },
    nombreDonsEffectues: 0,
  },
  {
    id: "don_seynabou_diallo",
    nom: "Seynabou Diallo",
    telephone: "+221 77 123 45 07",
    groupeSanguin: "O-",
    canalAlertePrefere: "SMS",
    statutVerification: "VERIFIE",
    disponible: true,
    // Thiès — couvre les demandes de etab_hopital_thies dans un rayon réaliste.
    position: { lat: 14.8037, lng: -16.9402 },
    nombreDonsEffectues: 3,
  },
  {
    id: "don_cheikh_sarr",
    nom: "Cheikh Sarr",
    telephone: "+221 77 123 45 08",
    groupeSanguin: "A+",
    canalAlertePrefere: "PUSH",
    statutVerification: "VERIFIE",
    disponible: true,
    // Thiès — couvre les demandes de etab_hopital_thies dans un rayon réaliste.
    position: { lat: 14.7735, lng: -16.9021 },
    nombreDonsEffectues: 5,
  },
];
